//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace starshipxac.Shell.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("starshipxac.Shell.Properties.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateHardLinkError {
            get {
                return ResourceManager.GetString("CreateHardLinkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CreateSymbolicLinkError {
            get {
                return ResourceManager.GetString("CreateSymbolicLinkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileOrDirectoryInfoIsNull {
            get {
                return ResourceManager.GetString("FileOrDirectoryInfoIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileOrDirectoryNameIsEmpty {
            get {
                return ResourceManager.GetString("FileOrDirectoryNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileOrDirectoryNameIsNull {
            get {
                return ResourceManager.GetString("FileOrDirectoryNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FilePathNotExist {
            get {
                return ResourceManager.GetString("FilePathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InvalidReferencePath {
            get {
                return ResourceManager.GetString("InvalidReferencePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KnownFolder Invalid GUID. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KnownFolderInvalidGuid {
            get {
                return ResourceManager.GetString("KnownFolderInvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KnownFolderParsingName {
            get {
                return ResourceManager.GetString("KnownFolderParsingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LinkDirectoryNameIsEmpty {
            get {
                return ResourceManager.GetString("LinkDirectoryNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LinkFileNameIsEmpty {
            get {
                return ResourceManager.GetString("LinkFileNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageListenerCannotCreateWindow {
            get {
                return ResourceManager.GetString("MessageListenerCannotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageListenerClassNotRegistered {
            get {
                return ResourceManager.GetString("MessageListenerClassNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageListenerFilterUnableToRegister {
            get {
                return ResourceManager.GetString("MessageListenerFilterUnableToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageListenerFilterUnknownListenerHandle {
            get {
                return ResourceManager.GetString("MessageListenerFilterUnknownListenerHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageListenerNoWindowHandle {
            get {
                return ResourceManager.GetString("MessageListenerNoWindowHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenStreamError {
            get {
                return ResourceManager.GetString("OpenStreamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PropertyCollectionCanonicalInvalidIndex {
            get {
                return ResourceManager.GetString("PropertyCollectionCanonicalInvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PropertyCollectionInvalidIndex {
            get {
                return ResourceManager.GetString("PropertyCollectionInvalidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PropertyCollectionNullCanonicalName {
            get {
                return ResourceManager.GetString("PropertyCollectionNullCanonicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PropVariantMultiDimArray {
            get {
                return ResourceManager.GetString("PropVariantMultiDimArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PropVariantNullString {
            get {
                return ResourceManager.GetString("PropVariantNullString", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PropVariantTypeNotSupported {
            get {
                return ResourceManager.GetString("PropVariantTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PropVariantUnsupportedType {
            get {
                return ResourceManager.GetString("PropVariantUnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveFileNullItem {
            get {
                return ResourceManager.GetString("SaveFileNullItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchConditionFactoryInvalidProperty {
            get {
                return ResourceManager.GetString("SearchConditionFactoryInvalidProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellFactoryUnableToCreateItem {
            get {
                return ResourceManager.GetString("ShellFactoryUnableToCreateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to get parsing name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellHelperGetParsingNameFailed {
            get {
                return ResourceManager.GetString("ShellHelperGetParsingNameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellInvalidCanonicalName {
            get {
                return ResourceManager.GetString("ShellInvalidCanonicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to get display name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellItemCannotGetDisplayName {
            get {
                return ResourceManager.GetString("ShellItemCannotGetDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellLibraryDefaultSaveFolderNotFound {
            get {
                return ResourceManager.GetString("ShellLibraryDefaultSaveFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellLibraryFolderNotFound {
            get {
                return ResourceManager.GetString("ShellLibraryFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellLibraryInvalidFolderType {
            get {
                return ResourceManager.GetString("ShellLibraryInvalidFolderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellLibraryInvalidLibrary {
            get {
                return ResourceManager.GetString("ShellLibraryInvalidLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellObjectCreationFailed {
            get {
                return ResourceManager.GetString("ShellObjectCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellObjectWatcherRegisterFailed {
            get {
                return ResourceManager.GetString("ShellObjectWatcherRegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellObjectWatcherUnableToChangeEvents {
            get {
                return ResourceManager.GetString("ShellObjectWatcherUnableToChangeEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellPropertyCannotSetProperty {
            get {
                return ResourceManager.GetString("ShellPropertyCannotSetProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ShellPropertyDescription error.: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellPropertyDescriptionError {
            get {
                return ResourceManager.GetString("ShellPropertyDescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ShellProperty constructor not found: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellPropertyFactoryConstructorNotFound {
            get {
                return ResourceManager.GetString("ShellPropertyFactoryConstructorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellPropertySetValue {
            get {
                return ResourceManager.GetString("ShellPropertySetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellPropertyUnableToGetWritableProperty {
            get {
                return ResourceManager.GetString("ShellPropertyUnableToGetWritableProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ShellProperty value type unmach: {0}, actual type {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellPropertyUnmatchValueType {
            get {
                return ResourceManager.GetString("ShellPropertyUnmatchValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellPropertyValueTruncated {
            get {
                return ResourceManager.GetString("ShellPropertyValueTruncated", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellPropertyWrongType {
            get {
                return ResourceManager.GetString("ShellPropertyWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellSearchFolderUnableToSetSortColumns {
            get {
                return ResourceManager.GetString("ShellSearchFolderUnableToSetSortColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellSearchFolderUnableToSetVisibleColumns {
            get {
                return ResourceManager.GetString("ShellSearchFolderUnableToSetVisibleColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellThumbnailDoesNotHaveThumbnail {
            get {
                return ResourceManager.GetString("ShellThumbnailDoesNotHaveThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellThumbnailNoHandler {
            get {
                return ResourceManager.GetString("ShellThumbnailNoHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ShellWatcherManagerFilterUnableToRegister に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellWatcherManagerFilterUnableToRegister {
            get {
                return ResourceManager.GetString("ShellWatcherManagerFilterUnableToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ShellWatcherRegisterFailed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellWatcherRegisterFailed {
            get {
                return ResourceManager.GetString("ShellWatcherRegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ShellWatcherUnableToChangeEvents に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ShellWatcherUnableToChangeEvents {
            get {
                return ResourceManager.GetString("ShellWatcherUnableToChangeEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StockIconInvalidGuid {
            get {
                return ResourceManager.GetString("StockIconInvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StreamEnumerationError {
            get {
                return ResourceManager.GetString("StreamEnumerationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StreamNameIsEmpty {
            get {
                return ResourceManager.GetString("StreamNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StreamNameIsNull {
            get {
                return ResourceManager.GetString("StreamNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TargetDirectoryNameIsEmpty {
            get {
                return ResourceManager.GetString("TargetDirectoryNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TargetFileNameIsEmpty {
            get {
                return ResourceManager.GetString("TargetFileNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TargetFileNotFound {
            get {
                return ResourceManager.GetString("TargetFileNotFound", resourceCulture);
            }
        }
    }
}
