//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace starshipxac.Windows.Shell.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("starshipxac.Windows.Shell.Properties.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ComboBoxIndexOutsideBounds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ComboBoxIndexOutsideBounds {
            get {
                return ResourceManager.GetString("ComboBoxIndexOutsideBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DialogCollectionCannotHaveDuplicateNames に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogCollectionCannotHaveDuplicateNames {
            get {
                return ResourceManager.GetString("DialogCollectionCannotHaveDuplicateNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DialogCollectionControlAlreadyHosted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogCollectionControlAlreadyHosted {
            get {
                return ResourceManager.GetString("DialogCollectionControlAlreadyHosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DialogCollectionModifyShowingDialog に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogCollectionModifyShowingDialog {
            get {
                return ResourceManager.GetString("DialogCollectionModifyShowingDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DialogControlCollectionCannotRemoveControls に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogControlCollectionCannotRemoveControls {
            get {
                return ResourceManager.GetString("DialogControlCollectionCannotRemoveControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DialogControlCollectionEmptyName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogControlCollectionEmptyName {
            get {
                return ResourceManager.GetString("DialogControlCollectionEmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DialogControlCollectionMenuItemControlsCannotBeAdded に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogControlCollectionMenuItemControlsCannotBeAdded {
            get {
                return ResourceManager.GetString("DialogControlCollectionMenuItemControlsCannotBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DialogControlCollectionModifyingControls に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogControlCollectionModifyingControls {
            get {
                return ResourceManager.GetString("DialogControlCollectionModifyingControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DialogControlCollectionMoreThanOneControl に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogControlCollectionMoreThanOneControl {
            get {
                return ResourceManager.GetString("DialogControlCollectionMoreThanOneControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DialogControlCollectionRemoveControlFirst に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogControlCollectionRemoveControlFirst {
            get {
                return ResourceManager.GetString("DialogControlCollectionRemoveControlFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Explorer Get Icon Size Error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExplorerGetIconSizeError {
            get {
                return ResourceManager.GetString("ExplorerGetIconSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Explorer Get Item Count Error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExplorerGetItemCountError {
            get {
                return ResourceManager.GetString("ExplorerGetItemCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Explorer Get Items Error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExplorerGetItemsError {
            get {
                return ResourceManager.GetString("ExplorerGetItemsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Explorer Get Selected Item Count Error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExplorerGetSelectedItemCountError {
            get {
                return ResourceManager.GetString("ExplorerGetSelectedItemCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Explorer Get Selected Items Error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExplorerGetSelectedItemsError {
            get {
                return ResourceManager.GetString("ExplorerGetSelectedItemsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Explorer Get View Error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExplorerGetViewError {
            get {
                return ResourceManager.GetString("ExplorerGetViewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Explorer Get View Mode Error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExplorerGetViewModeError {
            get {
                return ResourceManager.GetString("ExplorerGetViewModeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Explorer Navigation Failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExplorerNavigationFailed {
            get {
                return ResourceManager.GetString("ExplorerNavigationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Explorer Set Icon Size Error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExplorerSetIconSizeError {
            get {
                return ResourceManager.GetString("ExplorerSetIconSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NotImplementedException に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotImplementedException {
            get {
                return ResourceManager.GetString("NotImplementedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}Property cannot be changed during a dialog showing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PropertyChannotBeChanged {
            get {
                return ResourceManager.GetString("PropertyChannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RadioButtonListIndexOutOfBounds に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RadioButtonListIndexOutOfBounds {
            get {
                return ResourceManager.GetString("RadioButtonListIndexOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StockIconInvalidGuid に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StockIconInvalidGuid {
            get {
                return ResourceManager.GetString("StockIconInvalidGuid", resourceCulture);
            }
        }
    }
}
